### ISSUE TITLE
Node errors

### ISSUE THREAD

**Issue by linkit87** [SassDoc/sassdoc#159]
``` bash
[2014-08-06 08:47:37] [ERROR] TypeError: Cannot read property 'description' of undefined
    at Object.module.exports.markdown (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/sassdoc-theme-default/node_modules/sassdoc-theme-light/node_modules/sassdoc-filter/index.js:12:53)
    at Object.module.exports [as theme] (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/sassdoc-theme-default/node_modules/sassdoc-theme-light/index.js:34:10)
    at /Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/src/api.js:36:30
    at _fulfilled (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/q/q.js:749:13)
    at /Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/q/q.js:557:44
    at flush (/Users/user/.nvm/v0.10.29/lib/node_modules/sassdoc/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by kerryj89** [comment]
For anyone landing on this error make sure you wrap your types around curly brackets like {string} instead of (string).
