### ISSUE TITLE
Third parties integration issues

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#360]
Following of #354 somehow.

Keeping a record of found issues while using SassDoc programmatically, thus Grunt and Broccoli plugins are direct targets. Might also happen when integrating with Gulp.

1. Issue between `grunt-sassdoc` and `grunt-gh-pages`:
Although we are using `6to5` self-contained mode, there's still something going wrong with packages that hijack the global scope or natives.  
In this case the `collections` package.
```
Warning: Object function (a) {
      return is.string(a) || is.array(a);
    } has no method 'toArray' Use --force to continue.
TypeError: Object function (a) {
      return is.string(a) || is.array(a);
    } has no method 'toArray'
    at Function.Array.unzip (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/shim-array.js:35:24)
    at Array.GenericCollection.zip (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/generic-collection.js:199:18)
    at Array.GenericOrder.equals (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/generic-order.js:22:14)
    at Array.depth (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/shim-array.js:213:46)
    at Object.equals (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/shim-object.js:376:18)
    at Array.equals (/[...]/node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/shim-array.js:121:30)
    at Object.<anonymous> (/[...]/node_modules/grunt-sassdoc/node_modules/sassdoc/node_modules/6to5-runtime/core-js.js:135:17)
    at /[...]/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/sassdoc.js:394:27
    at sassdoc (/[...]/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/sassdoc.js:130:38)
    at compile (/[...]/node_modules/grunt-sassdoc/tasks/sassdoc.js:57:7)
```

**Comment by valeriangalliat** [comment]
At first sight looks like there's a problem with [this line](https://github.com/SassDoc/sassdoc/blob/c797a1b91eb1f591cf7b5b00f47b9598e3889d5c/src/sassdoc.js#L306) indirectly… but I don't know why this anonymous arrow function would be passed somewhere and called `toArray` on.

**Comment by pascalduez** [comment]
`return srcEnv(documentize, stream).apply(undefined, _to5Helpers.toArray(args));`

**Comment by valeriangalliat** [comment]
I don't think this is related, `_to5Helpers` is really not supposed to be a reference to the `is.string(a) || is.array(a)` arrow function…

**Comment by valeriangalliat** [comment]
To keep track:

```js
require('./node_modules/grunt-gh-pages/node_modules/q-io/node_modules/collections/shim-array')
var _core = require('./node_modules/sassdoc/node_modules/6to5-runtime/core-js')

console.log(_core.Array.find([['foo']], function (x) {
  return false
}))
```

So, `collections/shim-array` is not compatible with `6to5-runtime/core-js` (`selfContained` mode). The first one is modifying the global state while the second doesn't.

**Comment by HugoGiraudel** [comment]
What is the current state on this? Is this 2.1?

**Comment by pascalduez** [comment]
No milestone needed, it's not a task it's a reminder.

**Comment by HugoGiraudel** [comment]
Do you still need a remember on this?
