### ISSUE TITLE
Code preview for Sass syntax

### ISSUE THREAD

**Issue by CREEATION** [SassDoc/sassdoc#376]
Hello there,

as I'm using the Sass syntax, not SCSS, it would be really cool to also output Sass instead of SCSS in the docs. It doesn't make much sense to have Sass syntax source code and an SCSS documentation. :P

- Thomas

**Comment by pascalduez** [comment]
Hi,

the Parser is expecting the SCSS syntax to be able to correctly delimit code blocks. So at the moment this is not possible. 
Related #236

**Comment by valeriangalliat** [comment]
Hey,

The fact is SassDoc doesn't directly supports Sass syntax; internally it is converting Sass to SCSS using [sass-convert](https://github.com/SassDoc/sass-convert) and SassDoc works from the converted SCSS code.

We're aware of this issue, and I agree it's a kinda surprising behavior that's only due on how SassDoc works internally with Sass files, but we consider it's kinda an edge case and it's not in our short term plans.

However we aborded this subject [at some point](https://github.com/SassDoc/sassdoc/issues/39) and while the related issue is closed, we would still happily accept a PR with a `sass-comment-parser` support.

**Comment by pascalduez** [comment]
Fucked idea of the month: 
a `sassdoc-extras` filter that convert the code blocks back to Sass with `sass-convert` :trollface:

**Comment by valeriangalliat** [comment]
> Fucked idea of the month:
> a `sassdoc-extras` filter that convert the code blocks back to Sass with sass-convert :trollface:

Haha this is the best Quick & Dirty™ fix for this issue I can imagine. :smile:

**Comment by CREEATION** [comment]
:+1: :D

**Comment by HugoGiraudel** [comment]
Not a priority. We'll tackle this for 2.3 or later

**Comment by pascalduez** [comment]
The Quick & Dirty™ fix is not going to happen. That would mean opening a child-process for each code snippet, definitely a no go. 
If `sass-comment-parser` would be the preferred solution.

**Comment by HugoGiraudel** [comment]
I'm still not willing to spend time on this. Do you guys (@SassDoc/owners) think it is necessary?

**Comment by valeriangalliat** [comment]
I have no idea of a clean solution right now, apart from writing a sass-comment-parser. If we see a large amount of +1s on this issue, I'm okay to spend some time on this, but otherwise I think it's not necessary.

**Comment by pascalduez** [comment]
> I have no idea of a clean solution right now, apart from writing a sass-comment-parser. If we see a large amount of +1s on this issue, I'm okay to spend some time on this, but otherwise I think it's not necessary.

++

**Comment by misscs** [comment]
+1 this issue. Somewhat relatedly, I'm running into an issue where `sass-convert` cannot successfully run: 

```
» [ERROR] Error: spawn bundle exec sass-convert ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1038:32)
    at child_process.js:1129:20
    at process._tickCallback (node.js:372:11)
```

**Comment by valeriangalliat** [comment]
Hi @misscs, this is not related to the Sass syntax in code preview issue. It's an issue with sass-convert Node.js bindings, so I moved it [here](https://github.com/SassDoc/sass-convert/issues/10).

**Comment by misscs** [comment]
Ah, thanks!


On Fri, May 1, 2015, at 14:06, Valérian Galliat wrote:
> Hi @misscs[1], this is not related to the Sass syntax in code preview
> issue. It's an issue with sass-convert Node.js bindings, so I moved it
> here[2].


> — Reply to this email directly or view it on GitHub[3].

>


Links:

  1. https://github.com/misscs
  2. https://github.com/SassDoc/sass-convert/issues/10
  3. https://github.com/SassDoc/sassdoc/issues/376#issuecomment-98190094

**Comment by HugoGiraudel** [comment]
This has been open for 2 years, and I don’t think there is much more of a solution than last time we discussed it. Shall we close this @SassDoc/owners?
