### ISSUE TITLE
Custom theme: Error: SassDocError: Given theme is [object Undefined], expected [object Undefined]

### ISSUE THREAD

**Issue by makabde** [SassDoc/sassdoc#471]
I started to work on a custom theme (with Handlebars as a theme engine).
I am having issues when trying to run the `sassdoc` command from a gulp task. I am using the `ES6` notation for the `Gulpfile` and the theme `index` file but I have been facing the same issue for the last hours without any real luck to fix.

```bash
[15:16:19] Error: SassDocError: Given theme is [object Undefined], expected [object Undefined].
    at formatError (~/.nvm/versions/node/v6.9.1/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)
    at Gulp.<anonymous> (~/.nvm/versions/node/v6.9.1/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Object.error (~/Projects/opensource/sassdoc-theme-clear/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (~/Projects/opensource/sassdoc-theme-clear/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (~/Projects/opensource/sassdoc-theme-clear/node_modules/once/once.js:25:25)
    at f (~/Projects/opensource/sassdoc-theme-clear/node_modules/once/once.js:25:25)
    at done (~/Projects/opensource/sassdoc-theme-clear/node_modules/async-done/index.js:24:15)
    at Domain.onError (~/Projects/opensource/sassdoc-theme-clear/node_modules/async-done/index.js:32:12)
    at Domain.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
    at Domain.errorHandler [as _errorHandler] (domain.js:113:21)
    at process._fatalException (bootstrap_node.js:293:33)
```

My temporary gulp task:
```js
gulp.task('build:dev', done => {
  let _config = {
    cache: false,
    dest: path.resolve(__dirname, 'tmp'),
    theme: path.resolve(__dirname, 'src'),
    verbose: true
  };

 let _stream = sassdoc(_config);

  // gutil.log('Sassdoc config:\n', _config);

  gulp.src('src/scss/**/*.scss')
    .pipe(_stream)
    .on('end', () => {
      gutil.log('End of parsing phase');
    });

  _stream.promise.then(
    () => {
      gutil.log('End of documentation process');
      done();
    },
    (e) => {
      gutil.log('error:' + e);
    }
  );
});
```

And so far my index file looks like this
```js
import def            from '../default';

import { Promise }    from 'bluebird';
import extend         from 'extend';
import fse            from 'fs-extra';
import Handlebars     from 'handlebars';
import path           from 'path';
import sassdocExtras  from 'sassdoc-extras';

const copy            = Promise.promisify(fse.copy);
const renderFile      = Promise.promisify(Handlebars.compile);

const applyDefaults = ctx => {
  extend({}, def, ctx, {
    display: extend(def.display, ctx.display),
    groups: extend(def.groups, ctx.groups)
  });
};

const shortcutIcon = (dest, ctx) => {
  if (!ctx.shortcutIcon) {
    ctx.shortcutIcon = { type: 'internal', url: 'assets/images/favicon.png' };
  } else if (ctx.shortcutIcon.type === 'internal') {
    ctx.shortcutIcon.url = 'assets/images/' + ctx.shortcutIcon.url;

    return () =>
      copy(ctx.shortcutIcon.path, path.resolve(dest, ctx.shortcutIcon.url));
  }
};

export default (dest, ctx) => {
  ctx = applyDefaults(ctx);

  sassdocExtras(ctx,
    'description',
    'markdown',
    'display',
    'groupName',
    'shortcutIcon',
    'sort',
    'resolveVariables'
  );

  ctx.data.byGroupAndType = sassdocExtras.byGroupAndType(ctx.data);

  // Avoid key collision with Handlebars default `data`.
  // @see https://github.com/SassDoc/generator-sassdoc-theme/issues/22
  ctx._data = ctx.data;
  delete ctx.data;

  const index = path.resolve(__dirname, 'views/index.hbs');

  let promises = [
    copy(path.resolve(__dirname, '../assets'), path.resolve(dest, 'assets'))
      .then(shortcutIcon(dest, ctx)),

    renderFile(index, ctx)
  ];

  return Promise.all(promises);
};
```

**Comment by pascalduez** [comment]
Hi,

just a quick idea, I might be wrong, you're doing some Babeling as far as  I can see? The default export will be transpiled to `module.exports.default = function` instead of the `module.exports = function` expected by SassDoc.

**Comment by makabde** [comment]
You are right 👍  I just changed `export default...` to `module.exports = (dest, ctx) =>` in the index file and the error described has disappeared. Now I am having an other about a missing `descriptionPath`. Hopefully I should be able to fix it :)

**Comment by HugoGiraudel** [comment]
I’m going to close this then. :)
