### ISSUE TITLE
Deal with scoped packages for themes

### ISSUE THREAD

**Issue by chrisopedia** [SassDoc/sassdoc#514]
It seems that when you create a theme that is scoped (ie `@chrisopedia/sassdoc-theme-blah`), sassdoc doesn't seem to find it.  Is there a work around?

**Comment by pascalduez** [comment]
Hi @chrisopedia,

if your's willing to test the branch from #515, would ne interesting.

**Comment by chrisopedia** [comment]
@pascalduez I tried this in my source files package, ran it and I get the following error:

```
module.js:472
    throw err;
    ^

Error: Cannot find module './dist/sassdoc'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chrisopedia/Code/frontendgine/legion/styles/node_modules/sassdoc/index.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)```

**Comment by pascalduez** [comment]
`sassdoc@2.4.0`

**Comment by chrisopedia** [comment]
Thanks @pascalduez. Is there any new setup?  It still doesn't seem to find my theme.

**Comment by chrisopedia** [comment]
I think I figured it out.  It needs to be set with the scope in it.
